name: Create Stable Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Version increment level'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install release-it and plugins
        run: |
          npm install -g release-it@latest
          npm install -g @release-it/keep-a-changelog@latest

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Validate branch
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ "$BRANCH_NAME" != "main" ]]; then
            echo "Error: Stable releases can only be created from main branch"
            exit 1
          fi

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release-it ${{ inputs.level }} --ci --plugins.@release-it/keep-a-changelog.addVersionUrl=true

      - name: Display release information
        run: |
          echo "✅ Stable release completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Type: stable"
          echo "Level: ${{ inputs.level }}"
          echo ""
          echo "🔗 Check the release: https://github.com/${{ github.repository }}/releases"
          echo "🏷️ View tags: https://github.com/${{ github.repository }}/tags"